In [14]:
# write a python program to create an array and perform addition of two matrices
import numpy as np

## create two matrices
A = ([[1,2],[3,4]])
B = ([[5,6],[7,8]])
result = [[A[i][j] + B[i][j] for j in range (len(A[0]))]
          for i in range (len(A))
         ]

print("Matrix 1: ", A)
print("Matrix 2: ", B)
print("\nSum of Matrix 1 and Matrix 2 for list addition: ", result)


result_np = np.array(A)+np.array(B)
print("\nSum of Matrix 1 and Matrix 2 for numpy addition: ")
print(result_np)

Matrix 1:  [[1, 2], [3, 4]]
Matrix 2:  [[5, 6], [7, 8]]

Sum of Matrix 1 and Matrix 2 for list addition:  [[6, 8], [10, 12]]

Sum of Matrix 1 and Matrix 2 for numpy addition: 
[[ 6  8]
 [10 12]]


In [15]:
# write a python program to create an array and perform addition of two matrices
import numpy as np

## create two matrices
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

## add the matrices
C = A + B
print("Matrix A: ")
print(A)
print("Matrix B: ")
print(B)
print("Addition of two matrices: ")
print(C)

Matrix A: 
[[1 2]
 [3 4]]
Matrix B: 
[[5 6]
 [7 8]]
Addition of two matrices: 
[[ 6  8]
 [10 12]]
