In [1]:
# write a python program to create an array and perform addition of two matrices
import numpy as np

## create two matrices
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

## add the matrices
C = A + B
print("Matrix A: ")
print(A)
print("Matrix B: ")
print(B)
print("Addition of two matries: ")
print(C)

Matrix A: 
[[1 2]
 [3 4]]
Matrix B: 
[[5 6]
 [7 8]]
Addition of two matries: 
[[ 6  8]
 [10 12]]
